#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "hcoelho"
email = "henriquescharlaucoelho@gmail.com"

[ui]
editor = "nvim"

[aliases]
tug = ["bookmark", "advance", "--to", "closest_pushable(@)"]

[revset-aliases]
"closest_pushable(to)" = "heads(::to & mutable() & ~description(exact:\"\") & (~empty() | merges()))"

[[--scope]]
--when.platforms = ["unix"]  
[--scope.ui]
default-command = ["logstatus"]
diff-formatter = ["difft", "--color=always", "$left", "$right"]
[--scope.aliases]
logstatus = ["util", "exec", "--", "sh", "-c", "jj status && jj log -n 10"]
