#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "hcoelho"
email = "henriquescharlaucoelho@gmail.com"

[ui]
editor = "nvim"

[merge-tools.hunk]
program = "nvim"
edit-args = ["-c", "DiffEditor $left $right $output"]

[aliases]
tug = ["bookmark", "advance", "--to", "closest_pushable(@)"]

[revset-aliases]
"closest_pushable(to)" = "heads(::to & mutable() & ~description(exact:\"\") & (~empty() | merges()))"

[[--scope]]
--when.platforms = ["unix"]  
[--scope.ui]
default-command = ["logstatus"]
diff-formatter = ["difft", "--color=always", "$left", "$right"]
[--scope.aliases]
logstatus = ["util", "exec", "--", "sh", "-c", "jj status && jj log -n 10"]
[--scope.merge-tools.neovim]
program = "sh"
edit-args = [
  "-c",
  """
    set -eu
    rm -f "$right/JJ-INSTRUCTIONS"
    git -C "$left" init -q
    git -C "$left" add -A
    git -C "$left" commit -q -m baseline --allow-empty # create parent commit
    mv "$left/.git" "$right"
    git -C "$right" add --intent-to-add -A # create current working copy
    (cd "$right"; nvim)
    git -C "$right" diff-index --quiet --cached HEAD && { echo "No changes done, aborting split."; exit 1; }
    git -C "$right" commit -q -m split # create commit on top of parent including changes
    git -C "$right" restore . # undo changes in modified files
    git -C "$right" reset .   # undo --intent-to-add
    git -C "$right" clean -q -df # remove untracked files
  """
]
