foreground #000000
background #FBF0D9

color0 #000000
color8 #504945
color1 #8a0011
color9 #ba51ad
color2  #335200
color10 #6a8d45
color3  #937e44
color11 #937e44
color4  #014983
color12 #4784c2
color5  #79076f
color13 #ba51ad
color6  #025449
color14 #4b8e82
color7  #E6DBC5
color15 #FBF0D9
mark1_background #E0D3AF
mark2_foreground #000000
mark2_background #F2EBDC
mark3_foreground #000000
mark3_background #79076f
selection_foreground #000000
selection_background #E0D3AF
cursor #504945
cursor_text_color #FBF0D9
inactive_border_color #E6DBC5
bell_border_color #8a0011
active_tab_foreground   #000000
active_tab_background   #E6DBC5
inactive_tab_foreground #928374
inactive_tab_background #F2EBDC
