foreground #000000
background #FBF0D9

color0 #000000
color8 #504945
color1 #8B1A1A
color9 #A0416A
color2  #4B7A47
color10 #4B7A47
color3  #996D00
color11 #996D00
color4  #2D5B8E
color12 #2D5B8E
color5  #7A4A80
color13 #A0416A
color6  #2A7B7B
color14 #2A7B7B
color7  #E6DBC5
color15 #FBF0D9
mark1_background #E0D3AF
mark2_foreground #000000
mark2_background #F2EBDC
mark3_foreground #000000
mark3_background #7A4A80
selection_foreground #000000
selection_background #E0D3AF
cursor #504945
cursor_text_color #FBF0D9
inactive_border_color #E6DBC5
bell_border_color #8B1A1A
active_tab_foreground   #000000
active_tab_background   #E6DBC5
inactive_tab_foreground #928374
inactive_tab_background #F2EBDC
