[tools]
dotenvx = "latest"
jj = "latest"
node = ["24.11.1", "dev_tools"]
rust = "latest"
usage = "latest"
"npm:obsidian-headless" = { version = "latest", depends = ["node@dev_tools"] }

[tool_alias.node.versions]
dev_tools = "24.14.1"

