# book theme — light/paper palette

[colors]
background = '#FBF0D9'
foreground = '#000000'

# Selection
selection-background = '#E0D3AF'
selection-foreground = '#000000'

# Navigation
tabs-active = '#E6DBC5'
tabs-active-foreground = '#000000'
tabs-active-highlight = '#8a0011'
bar = '#F2EBDC'
split = '#928374'
cursor = '#8a0011'
vi-cursor = '#014983'

# Search
search-match-background = '#937e44'
search-match-foreground = '#FBF0D9'
search-focused-match-background = '#8a0011'
search-focused-match-foreground = '#FBF0D9'

# Regular colors
black = '#000000'
blue = '#014983'
cyan = '#025449'
green = '#335200'
magenta = '#79076f'
red = '#8a0011'
tabs = '#F2EBDC'
white = '#928374'
yellow = '#937e44'

# Dim colors
dim-black = '#504945'
dim-blue = '#014983'
dim-cyan = '#025449'
dim-foreground = '#928374'
dim-green = '#335200'
dim-magenta = '#79076f'
dim-red = '#cf504b'
dim-white = '#E6DBC5'
dim-yellow = '#937e44'

# Light colors
light-black = '#504945'
light-blue = '#014983'
light-cyan = '#025449'
light-foreground = '#504945'
light-green = '#335200'
light-magenta = '#ba51ad'
light-red = '#cf504b'
light-white = '#E6DBC5'
light-yellow = '#937e44'
