set -U fish_color_normal ffffff
set -U fish_color_command 5ef1ff
set -U fish_color_param ffaecf
set -U fish_color_keyword 5eff6c
set -U fish_color_quote f1ff5e
set -U fish_color_redirection 5ea1ff
set -U fish_color_end bd5eff
set -U fish_color_comment 7b8496
set -U fish_color_error ff6e5e
set -U fish_color_gray 7b8496
set -U fish_color_selection --background=3c4048
set -U fish_color_search_match --background=3c4048
set -U fish_color_option f1ff5e
set -U fish_color_operator 5ea1ff
set -U fish_color_escape ffaecf
set -U fish_color_autosuggestion 7b8496
set -U fish_color_cancel ff6e5e
set -U fish_color_cwd ffbd5e
set -U fish_color_user 5ef5d2
set -U fish_color_host 5eff6c
set -U fish_color_host_remote f1ff5e
set -U fish_color_status ff6e5e
set -U fish_pager_color_progress 7b8496
set -U fish_pager_color_prefix 5ea1ff
set -U fish_pager_color_completion ffffff
set -U fish_pager_color_description 7b8496
